services:
  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
    ports:
      - '3010:3010'
    depends_on:
      - api

  worker:
    build:
      context: .
      dockerfile: ./packages/worker/Dockerfile
    environment:
      - PORT=3001
      - LOG_LEVEL=verbose
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=block-explorer
      - BLOCKCHAIN_RPC_URL=https://mainnet.era.zksync.io
      - DATA_FETCHER_URL=http://data-fetcher:3040
      - BATCHES_PROCESSING_POLLING_INTERVAL=1000
    ports:
      - '3001:3001'

  data-fetcher:
    build:
      context: .
      dockerfile: ./packages/data-fetcher/Dockerfile
    environment:
      - PORT=3040
      - LOG_LEVEL=verbose
      - BLOCKCHAIN_RPC_URL=https://mainnet.era.zksync.io
    ports:
      - '3040:3040'

  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    environment:
      - PORT=3020
      - METRICS_PORT=3005
      - LOG_LEVEL=verbose
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/block-explorer
    ports:
      - '3020:3020'
      - '3005:3005'
    depends_on:
      - worker

  postgres:
    image: "postgres:14"
    logging:
      driver: none 
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=block-explorer


volumes:
  postgres: