name: API E2E tests

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  runE2ETests:
    name: Run E2E tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./packages/api
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Start docker containers
        run: |
          docker-compose -f "docker-compose.e2e.yaml" up -d --build

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --ignore-scripts

      - name: Run e2e tests
        run: |
          npm run test:e2e

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: "packages/api/e2e-junit.xml"
          check_run_annotations: all tests, skipped tests
          report_individual_runs: "true"
          check_name: API E2E Test Results

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.e2e.yaml" down