name: Deploy App to Production
"on":
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "A release version to deploy, e.g. v2.0.0"
        required: true
        default: "v2.0.0"
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Dist package
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{ github.event.inputs.version }}"
          file: "dist.zip"
          target: "dist.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip Dist package
        run: |
          unzip dist.zip -d packages/app

      - name: Update config
        run: |
          echo "window[\"##runtimeConfig\"] = { sentryDSN: \"${{ vars.SENTRY_DSN }}\"  };" > packages/app/dist/config.js

      - name: Download Storybook package
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "tags/${{ github.event.inputs.version }}"
          file: "storybook-static.zip"
          target: "storybook-static.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unzip Storybook package
        run: |
          unzip storybook-static.zip -d packages/app

      - name: Deploy
        id: deploy
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCAN_V2 }}'
          projectId: scan-v2
          channelID: live
          entryPoint: ./packages/app
