name: Node license check

on: pull_request

env:
  ALLOWED_LICENSES: >
    MIT;
    0BSD;
    BSD-2-Clause;
    BSD-3-Clause;
    ISC;
    Apache-2.0;
    Apache 2.0;
    MPL-2.0;
    CC0-1.0;
    CC-BY-3.0;
    CC-BY-4.0;
    Python-2.0;
    Artistic-2.0;
    Zlib;
    Unlicense;
    UNLICENSED;
    BlueOak-1.0.0;
  # gitconfiglocal@1.0.0 - BSD-3-Clause
  # glob-to-regexp@0.3.0 - BSD-2-Clause
  # map-stream@0.1.0 - MIT
  # It has to be one line, there must be no space between packages.
  EXCLUDE_PACKAGES: gitconfiglocal@1.0.0;glob-to-regexp@0.3.0;map-stream@0.1.0

jobs:
  generate-matrix:
    name: Lists modules
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          DIRS=$(find -not \( -path \*node_modules -prune \) -type f -name package.json  | xargs dirname | awk -v RS='' -v OFS='","' 'NF { $1 = $1; print "\"" $0 "\"" }')
          echo "matrix=[${DIRS}]" >> $GITHUB_OUTPUT
        id: set-matrix

  license-check:
    needs: [generate-matrix]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        dir: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install license checker
        run: npm install -g license-checker

      - name: Install dependencies
        run: npm ci

      - name: Check licenses in ${{ matrix.dir }}
        working-directory: ${{ matrix.dir }}
        run: npx license-checker --json --onlyAllow="$ALLOWED_LICENSES" --excludePackages "$EXCLUDE_PACKAGES"
