name: Validate PR

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  label:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        with:
          subjectPattern: ^(?![A-Z]).+$
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint -- -- --no-fix --max-warnings 0

      - name: App type check
        working-directory: ./packages/app
        run: |
          npm run typecheck

      - name: Test
        run: |
          npm run test:ci

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          files: |
            packages/app/junit.xml
            packages/api/junit.xml
            packages/worker/junit.xml
            packages/data-fetcher/junit.xml
          check_run_annotations: all tests, skipped tests
          report_individual_runs: "true"
          check_name: Unit Test Results

      - name: Build
        run: |
          npm run build
