import type { EnvironmentConfig } from ".";

const config: EnvironmentConfig = {
  networks: [
    {
      apiUrl: "https://block-explorer-api.testnets.zksync.dev",
      verificationApiUrl: "https://zksync2-testnet-explorer.zksync.dev",
      bridgeUrl: "https://staging.goerli.bridge.zksync.dev",
      hostnames: ["https://goerli.staging-scan-v2.zksync.dev"],
      icon: "/images/icons/zksync-arrows.svg",
      l1ExplorerUrl: "https://goerli.etherscan.io",
      l2ChainId: 280,
      l2NetworkName: "zkSync Era Testnet",
      l2WalletUrl: "https://goerli.staging-portal.zksync.dev/",
      maintenance: false,
      name: "goerli",
      newProverUrl: "https://storage.googleapis.com/zksync-era-testnet-proofs/proofs_fri",
      published: true,
      rpcUrl: "https://testnet.era.zksync.dev",
    },
    {
      apiUrl: "https://block-explorer-api.stage.zksync.dev",
      verificationApiUrl: "https://z2-dev-api-explorer.zksync.dev",
      hostnames: ["https://goerli-beta.staging-scan-v2.zksync.dev"],
      icon: "/images/icons/zksync-arrows.svg",
      l1ExplorerUrl: "https://goerli.etherscan.io",
      l2ChainId: 270,
      l2NetworkName: "Goerli (Stage2)",
      l2WalletUrl: "https://goerli-beta.staging-portal.zksync.dev/",
      maintenance: false,
      name: "goerli-beta",
      newProverUrl: "https://storage.googleapis.com/zksync-era-stage-proofs/proofs_fri",
      published: true,
      rpcUrl: "https://z2-dev-api.zksync.dev",
    },
    {
      apiUrl: "https://block-explorer-api.mainnet.zksync.io",
      verificationApiUrl: "https://zksync2-mainnet-explorer.zksync.io",
      bridgeUrl: "https://staging.bridge.zksync.dev",
      hostnames: ["https://staging-scan-v2.zksync.dev"],
      icon: "/images/icons/zksync-arrows.svg",
      l1ExplorerUrl: "https://etherscan.io",
      l2ChainId: 324,
      l2NetworkName: "zkSync Era Mainnet",
      l2WalletUrl: "https://staging-portal.zksync.dev/",
      maintenance: false,
      name: "mainnet",
      newProverUrl: "https://storage.googleapis.com/zksync-era-mainnet-proofs/proofs_fri",
      published: true,
      rpcUrl: "https://mainnet.era.zksync.io",
    },
  ],
};

export default config;
